#!/bin/bash
clear
sleep 1s

figlet "APLICATIVOS" | lolcat

echo -e "\033[1;37mPARA BAIXAR COPIE E COLE ONLINK NO NAVEGADOR \033[0m"


https://www.mediafire.com/file/1z4ahpu2o9zctn1/APLICATIVOS.zip/file


echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read