#!/bin/bash
    clear
    echo -e "\033[1;37m ATUALIZANDO BOT DE VENDAS️\033[0m"
    sleep 6s
unzip TBotPlusLOCKED.zip && cd TBotPlus; chmod +x TerminusBot.sh && ./TerminusBot.sh && wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash && source ~/.profile && nvm install 16 && terminus