#!/bin/bash
    clear
    echo -e "\033[1;37m  ⚠️AO FIM DA INSTALAÇÃO ATUALIZE O BOT⚠️\033[0m"
    sleep 6s
wget $HOME -O TBotPlusLOCKED.zip https://www.dropbox.com/s/61q6tvq76qyvsrd/TBotPlusLOCKED.zip?dl=0
echo -e "\033[1;37mINSTALADO️\033[0m"
    sleep 1s
    clear
    botzap