#!/bin/bash
    clear
    echo -e "\033[1;37m INICIANDO BOT
⚠️ ANTES DE USAR O BOT USE O COMANDO NA VPS⚠️ 👉 nvm install 16 👈️\033[0m"
    echo -e ""
    echo -e "\033[1;31m⚠️ SÓ USAR O BOT SE O COMANDO FOR USADO, CASO USE O BOT SEM O COMANDO E NÃO FUNCIONAR É SUA RESPONSABILIDADE ⚠️ ️\033[0m"
    sleep 15s
    terminus