#!/bin/bash
    clear
    echo -e "\033[1;37mFINALIZAR BOT DE VENDAS\033[0m"
    sleep 2s
    source ~/.profile && nvm install 16
echo -e "\033[1;37mFINALIZADO️\033[0m"
    sleep 1s
    clear
    botzap