#!/bin/bash
clear
sleep 1s

figlet "GL MOD" | lolcat

echo -e "\033[1;37mPARA BAIXAR COPIE E COLE ONLINK NO NAVEGADOR \033[0m"




https://www.mediafire.com/file/upxi6ulb5u4exua/GL_TUNNEL_MOD%25281%2529_%25282%2529.apk/file?dkey=vj01udt8itj&r=1074